config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "facilities#index"

  devise_for :users, path: "/", controllers: { confirmations: "confirmations" }
  resources :facilities do
    resources :indicators
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", via: :put, as: :update_user_confirmation
  end

  resources :users do
    member do
      post :resend_confirmation
      put :archive
      put :restore
    end
  end

  resource :locale, only: [:update]

  resources :languages
  resources :api_keys

  namespace :api do
    namespace :v1 do
      resources :facilities, only: [] do
        resources :indicators
      end

      get "*path" => "api#routing_error"
    end
  end
end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :uuid             not null, primary key
#  code       :string
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Language < ApplicationRecord
  validates :code, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: %i[ edit update destroy ]

  def index
    @pagy, @languages = pagy(Language.all)
  end

  def new
    @language = Language.new
  end

  def edit
  end

  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to languages_url, notice: "Language was successfully created." }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to languages_url, notice: "Language was successfully updated." }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url, notice: "Language was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_language
      @language = Language.find(params[:id])
    end

    def language_params
      params.require(:language).permit(:code, :name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.haml
.w-50.view-center
  = simple_form_for(@language) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      .mb-3= f.input :code, label: t('shared.code')
      .mb-3= f.input :name, label: t('shared.name')

    .form-actions
      = link_to t('shared.cancel'), languages_path, class: 'btn btn-secondary me-1'
      = f.submit t('shared.save'), class: 'btn btn-primary'

app/views/languages/edit.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('language.edit_language')
  = render 'form'

app/views/languages/index.html.haml
.container-fluid.px-4.facilities{'data-controller': "languages"}
  = render 'shared/header_title', title: t('language.languages')

  .d-flex.justify-content-end
    = render "shared/buttons/add_new_button", url: new_language_path, name: t("language.language")

  .mb-4.pretty
    = render "shared/no_data", items: @languages

    - if @languages.present?
      .table-responsive
        %table.table.table-hover.pretty
          %thead
            %tr
              %th #
              %th= t('shared.code')
              %th= t('shared.name')
              %th= t('shared.created_at')
              %th= t('shared.updated_at')
              %th

          %tbody
            - @languages.each_with_index do |language, index|
              %tr
                %td= @pagy.from + index
                %td= language.code
                %td= language.name
                %td= timeago(language.created_at).html_safe
                %td= timeago(language.updated_at).html_safe
                %td.d-flex.justify-content-end
                  = render 'shared/buttons/edit_button', object: language, url: edit_language_path(language)

                  = render 'shared/buttons/delete_button', object: language, message: { type: t('language.language'), name: language.name, url: language_path(language) }

      - if @pagy.pages > 1
        .pagy-wrapper.justify-content-lg-end.justify-content-center
          != pagy_bootstrap_compact_nav(@pagy)

= render "shared/modals/confirm_delete_modal"

app/views/languages/new.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('language.new_language')
  = render 'form'