config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "facilities#index"

  devise_for :users, path: "/", controllers: { confirmations: "confirmations" }
  resources :facilities do
    resources :indicators
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", via: :put, as: :update_user_confirmation
  end

  resources :users do
    member do
      post :resend_confirmation
      put :archive
      put :restore
    end
  end

  resource :locale, only: [:update]

  resources :languages
  resources :api_keys

  namespace :api do
    namespace :v1 do
      resources :facilities, only: [] do
        resources :indicators
      end

      get "*path" => "api#routing_error"
    end
  end
end

app/models/concerns/users/confirmable.rb
# frozen_string_literal: true

module Users::Confirmable
  extend ActiveSupport::Concern

  included do
    def password_match?
      errors[:password] << I18n.t("errors.messages.blank") if password.blank?
      errors[:password_confirmation] << I18n.t("errors.messages.blank") if password_confirmation.blank?
      errors[:password_confirmation] << I18n.translate("errors.messages.confirmation", attribute: "password") if password != password_confirmation

      password == password_confirmation && !password.blank?
    end

    # new function to set the password without knowing the current
    # password used in our confirmation controller.
    def attempt_set_password(params)
      self.password = params[:password]
      self.password_confirmation = params[:password_confirmation]
    end

    # new function to return whether a password has been set
    def no_password?
      encrypted_password.blank?
    end

    # Devise::Models:unless_confirmed` method doesn't exist in Devise 2.0.0 anymore.
    # Instead you should use `pending_any_confirmation`.
    def only_if_unconfirmed
      pending_any_confirmation { yield }
    end

    protected
      def password_required?
        confirmed? ? super : false
      end
  end
end

app/models/concerns/users/filter.rb
module Users::Filter
  extend ActiveSupport::Concern

  included do
    def self.filter(params)
      scope = all
      scope = scope.where("email LIKE ?", "%#{params[:email]}%") if params[:email].present?
      scope = scope.only_deleted if params[:archived] == "true"
      scope
    end
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :uuid             not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  role                   :integer
#  actived                :boolean          default(TRUE)
#  deleted_at             :datetime
#  locale                 :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  include Users::Filter
  include Users::Confirmable

  acts_as_paranoid

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :confirmable, :lockable, :trackable,
         :recoverable, :rememberable, :validatable

  enum role: {
    primary_admin: 1,
    admin: 2
  }

  validates :role, presence: true

  ROLES = [["Admin", "admin"]]

  def status
    return "archived" if deleted?
    return "locked" if access_locked?
    return "actived" if confirmed? && actived?
    return "deactivated" unless actived?

    "pending"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ edit update archive resend_confirmation]

  def index
    @pagy, @users = pagy(policy_scope(authorize User.filter(filter_params).order(sort_column + " " + sort_direction)))
  end

  def new
    @user = authorize User.new
  end

  def create
    @user = authorize User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User was successfully updated." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def archive
    @user.destroy

    redirect_to users_url, status: :see_other, notice: I18n.t("user.archive_successfully", email: @user.email)
  end

  def restore
    @user = authorize User.only_deleted.find(params[:id])
    @user.restore

    redirect_to users_url, notice: I18n.t("user.restore_successfully", email: @user.email)
  end

  def destroy
    @user = authorize User.only_deleted.find(params[:id])
    @user.really_destroy!

    redirect_to users_url(archived: true)
  end

  def resend_confirmation
    @user.send_confirmation_instructions

    redirect_to users_url, notice: I18n.t("user.resend_confirmation_successfully")
  end

  private
    def set_user
      @user = authorize User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:email, :actived, :role)
    end

    def filter_params
      params.permit(:email, :archived)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_action_buttons.haml
- if user.deleted?
  / Restore
  = link_to restore_user_path(user), class: "btn btn-circle btn-sm btn-outline-warning me-1", data: { 'bs-toggle': 'tooltip', 'bs-placement': 'top', turbo_method: :put }, title: t('shared.restore') do
    %i.fas.fa-trash-restore

  / Really destroy
  - if policy(user).destroy?
    = render 'shared/buttons/delete_button', object: user, message: { type: t('user.user'), name: user.email, url: user_path(user) }
  - else
    %button.disabled.btn.btn-circle.btn-sm.btn-outline-danger.me-1{data: {'bs-toggle': 'tooltip', 'bs-placement': 'top', title: t('user.cannnot_be_deleted')}}
      %i.fas.fa-trash-alt

- else
  - if policy(user).archive?
    - unless user.confirmed?
      / Resend confirmation
      = link_to resend_confirmation_user_path(user), class: "btn btn-circle btn-sm btn-outline-success me-1", data: { 'bs-toggle': 'tooltip', 'bs-placement': 'top', turbo_method: :post }, title: t('user.resend_confirmation') do
        %i.fas.fa-share-square

      / Copy confirm link
      %div{'data-controller': "users"}
        %input.confirm-link{ value: confirmation_url(user, confirmation_token: user.confirmation_token), 'data-users-target' => 'link', readonly: true }

        %button.me-1{ class: "btn btn-circle btn-sm btn-outline-secondary me-1 btn-copy", data: { action: "click->users#copyConfirmationLink", 'bs-toggle': 'tooltip', 'bs-placement': 'top', label: t('shared.copied') }, title: t('user.copy_confirm_link')}
          %i.far.fa-copy

    / Deactivate / Activate
    - if policy(user).update? && user.confirmed?
      - title = user.actived? ? t("shared.deactivate") : t("shared.activate")
      = link_to user_path(user, user: {actived: !user.actived}), class: "btn btn-circle btn-sm btn-outline-info me-1", data: { 'bs-toggle': 'tooltip', 'bs-placement': 'top', turbo_method: :put }, title: title do
        %i.fas{class: (user.actived? ? "fa-eye" : "fa-eye-slash")}

    / Edit
    = render 'shared/buttons/edit_button', object: user, url: edit_user_path(user)

    / Archive
    = link_to archive_user_path(user), class: "btn btn-circle btn-sm btn-outline-danger", data: {'bs-toggle': 'tooltip', 'bs-placement': 'top', turbo_method: :put}, title: t('shared.archive') do
      %i.fas.fa-user-times

app/views/users/_filter.html.haml
%form{ action: users_path, method: 'get' }
  .input-group.my-2.search-input
    = text_field_tag(:email, params[:email], class: 'form-control', placeholder: t('shared.email'))
    %span.input-group-text
      %i.fas.fa-search

  = hidden_field_tag :archived, params[:archived]

app/views/users/_form.html.haml
.w-50.view-center
  = simple_form_for @user do |f|
    / .d-flex
    /   .control{style: 'margin-right: -16px;'}
    /     = form_check_toggle({name: "user[actived]", checked: f.object.actived}).html_safe
    /   %label.flex-1= t('user.set_active')

    .mb-3= f.input :email, label: t('user.email'), input_html: { readonly: @user.persisted? }
    .mb-3= f.input :role, label: t('user.role'), collection: User::ROLES, input_html: { class: 'role custom-select' }, include_blank: false

    .actions
      = link_to t('shared.cancel'), users_path, class: 'btn btn-secondary me-1'
      = f.submit t('shared.save'), class: 'btn btn-primary'

app/views/users/_nav_tabs.html.haml
%ul.nav.nav-tabs
  %li.nav-item
    %a.nav-link{ href: users_path, class: ('active' if params[:archived].blank?) }= t("user.all")

  %li.nav-item
    %a.nav-link{href: users_path(archived: true), class: ('active' if params[:archived].present?)}= t("user.archived")

app/views/users/edit.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('user.edit_user')
  = render 'form'

app/views/users/index.html.haml
.container-fluid.px-4.facilities{'data-controller': "users"}
  = render 'shared/header_title', title: t('user.users')

  .d-flex.justify-content-end
    = render "shared/buttons/add_new_button", url: new_user_path, name: t("user.user")

  = render 'nav_tabs'
  = render 'filter'
  = render "shared/no_data", items: @users

  - if @users.present?
    = render "shared/pagination_title", objects: @users

    .table-responsive
      %table.table.table-hover.pretty
        %thead
          %tr
            %th #
            %th= sortable "email", t("user.email")
            %th= t('user.status')
            %th= t('user.role')
            %th= t('shared.created_at')
            %th= t('shared.updated_at')
            %th= t('user.last_sign_in_at')
            %th

        %tbody
          - @users.each_with_index do |user, index|
            %tr{class: ("disabled-bg" unless user.actived?)}
              %td= @pagy.from + index
              %td= user.email
              %td= user.role.try(:titlecase)
              %td.status{ class: user.status }
                = t("user.#{user.status}")
              %td= timeago(user.created_at).html_safe
              %td= timeago(user.updated_at).html_safe
              %td= timeago(user.last_sign_in_at).html_safe
              %td
                .d-flex.justify-content-end
                  = render 'action_buttons', user: user

    - if @pagy.pages > 1
      .pagy-wrapper.justify-content-lg-end.justify-content-center
        != pagy_bootstrap_compact_nav(@pagy)

= render "shared/modals/confirm_delete_modal"

app/views/users/new.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('user.new_user')
  = render 'form'

app/views/users/show.html.haml
= render "shared/modals/remote_modal", title: t('shared.confirm_delete', name: t('user.user')) do
  %div
    = t('shared.are_you_sure_to_delete', type: t('user.user'), name: @user.email).html_safe

  .d-flex.justify-content-end.mt-3
    = render "shared/buttons/modal_cancel_button"
    = render "shared/buttons/modal_delete_button", item: @user