config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "facilities#index"

  devise_for :users, path: "/", controllers: { confirmations: "confirmations" }
  resources :facilities do
    resources :indicators
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", via: :put, as: :update_user_confirmation
  end

  resources :users do
    member do
      post :resend_confirmation
      put :archive
      put :restore
    end
  end

  resource :locale, only: [:update]

  resources :languages
  resources :api_keys

  namespace :api do
    namespace :v1 do
      resources :facilities, only: [] do
        resources :indicators
      end

      get "*path" => "api#routing_error"
    end
  end
end

app/views/shared/_flash_message.html.haml
- if notice.present?
  .alert.alert-success.alert-dismissible.fade.show.notify-message.ml-2{:role => "alert"}
    = notice
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}


- if alert.present?
  .alert.alert-warning.alert-dismissible.fade.show.notify-message.ml-2{:role => "alert"}
    = alert
    %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "alert", :type => "button"}

:javascript
  setTimeout(function() {
    var alertList = document.querySelectorAll('.alert')
    alertList.forEach(function (alert) {
      alert.classList.remove('show')
    })
  }, 3000);

app/views/shared/_header_title.html.haml
%h1.h2.mt-4= title

app/views/shared/_no_data.html.haml
- url ||= ''
- label ||= t("shared.add_new")
- remote ||= false

- if items.blank?
  .text-center.no-data.m-4
    %h2= t('shared.no_data_found')

    - if items.length.zero? || policy(items.class.to_s.split("::")[0..-2].join('::').constantize).create? && !request.query_string.present?
      %p= t('shared.use_plus_to_add_item')

      - if url.present?
        = link_to url, remote: remote, class: "btn btn-primary btn-sm shadow-sm" do
          %i.fas.fa-plus.fa-sm.text-white-50
          = label

app/views/shared/_pagination_title.html.haml
.d-flex.flex-grow-1
  - if objects.present?
    .pagy-wrapper.justify-content-lg-end.justify-content-center
      .d-flex.flex-grow-1
        .flex-1.d-flex.align-items-center.mb-2
          %span= t('shared.pagination_title', from: @pagy.from, to: @pagy.to, total: number_with_delimiter(@pagy.count)).html_safe

  .flex-grow-1

  - if @pagy.pages > 1
    .d-lg-block.d-none
      != pagy_bootstrap_nav(@pagy)

app/views/shared/_sidebar.html.haml
%nav#sidenavAccordion.sb-sidenav.accordion.sb-sidenav-light
  .sb-sidenav-menu
    .nav
      / .sb-sidenav-menu-heading Core
      / %a.nav-link{:href => "index.html"}
      /   .sb-nav-link-icon
      /     %i.fas.fa-tachometer-alt
      /   Dashboard

      .sb-sidenav-menu-heading Interface

      = link_to users_path, class: ['nav-link', css_active_class('users')] do
        .sb-nav-link-icon
          %i.fa-solid.fa-users
        = t('sidebar.users')

      = link_to languages_path, class: ['nav-link', css_active_class('languages')] do
        .sb-nav-link-icon
          %i.fa-solid.fa-language
        = t('sidebar.languages')


      = link_to facilities_path, class: ['nav-link', css_active_class('facilities')] do
        .sb-nav-link-icon
          %i.fa-solid.fa-layer-group
        = t('sidebar.facilities')

      = link_to api_keys_path, class: ['nav-link', css_active_class('api_keys')] do
        .sb-nav-link-icon
          %i.fa-solid.fa-key
        = t('sidebar.api_keys')

      / %a.nav-link.collapsed{"aria-controls" => "collapseLayouts", "aria-expanded" => "false", "data-bs-target" => "#collapseLayouts", "data-bs-toggle" => "collapse", :href => "#"}
      /   .sb-nav-link-icon
      /     %i.fas.fa-columns
      /   Layouts
      /   .sb-sidenav-collapse-arrow
      /     %i.fas.fa-angle-down
      / #collapseLayouts.collapse{"aria-labelledby" => "headingOne", "data-bs-parent" => "#sidenavAccordion"}
      /   %nav.sb-sidenav-menu-nested.nav
      /     %a.nav-link{:href => "layout-static.html"} Static Navigation
      /     %a.nav-link{:href => "layout-sidenav-light.html"} Light Sidenav

  .sb-sidenav-footer
    .small Version 0.0.1

app/views/shared/_switch_language.html.haml
%ul.navbar-nav.ms-auto.ms-md-0.me-3.me-lg-4{'data-controller' => 'topbar' }

  %li.nav-item.dropdown
    %a#localeDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
      - locale = system_locales.select { |l| l[:code] == I18n.locale.to_s }.first

      = image_tag locale[:image], alt: locale[:label], size: "24x24"
      %span.text-gray-600.small= locale[:label]

    %ul.dropdown-menu.dropdown-menu-end{ "aria-labelledby" => "localeDropdown" }
      - system_locales.each_with_index do |locale, index|
        %li
          = link_to locale_path(locale: locale[:code]), method: :put, data: { remote: true, controller: 'topbar', action: "ajax:success->topbar#reloadPage" }, class: 'btn dropdown-item' do
            = image_tag locale[:image], alt: locale[:label], size: "24x24"
            = locale[:label]

        - if index < system_locales.length - 1
          %li
            %hr.dropdown-divider

app/views/shared/_topbar.html.haml
%nav.sb-topnav.navbar.navbar-expand.navbar-dark.bg-dark{'data-controller': "sidebar"}
  / Navbar Brand
  %a.navbar-brand.ps-3{ href: '#' } Scorecard Facility
  / Sidebar Toggle
  %button#sidebarToggle.btn.btn-link.btn-sm.order-1.order-lg-0.me-4.me-lg-0{:href => "#!", data: { action: "click->sidebar#toggle" } }
    %i.fas.fa-bars

  .d-md-inline-block.form-inline.ms-auto.me-0.me-md-3.my-2.my-md-0

  = render "shared/switch_language"

  / Navbar
  %ul.navbar-nav.ms-auto.ms-md-0.me-3.me-lg-4
    %li.nav-item.dropdown
      %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
        %i.fas.fa-user.fa-fw
      %ul.dropdown-menu.dropdown-menu-end{"aria-labelledby" => "navbarDropdown"}
        %li
          .dropdown-item= current_user.email
        %li
          %hr.dropdown-divider
        %li
          %a.dropdown-item{ href: destroy_user_session_path, data: { turbo_method: :delete } } Logout