config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "facilities#index"

  devise_for :users, path: "/", controllers: { confirmations: "confirmations" }
  resources :facilities do
    resources :indicators
  end

  # https://github.com/plataformatec/devise/wiki/How-To:-Override-confirmations-so-users-can-pick-their-own-passwords-as-part-of-confirmation-activation
  as :user do
    match "/confirmation" => "confirmations#update", via: :put, as: :update_user_confirmation
  end

  resources :users do
    member do
      post :resend_confirmation
      put :archive
      put :restore
    end
  end

  resource :locale, only: [:update]

  resources :languages
  resources :api_keys

  namespace :api do
    namespace :v1 do
      resources :facilities, only: [] do
        resources :indicators
      end

      get "*path" => "api#routing_error"
    end
  end
end

app/models/facility.rb
# == Schema Information
#
# Table name: facilities
#
#  id             :string           not null, primary key
#  name_en        :string
#  name_km        :string
#  abbr_en        :string
#  abbr_km        :string
#  parent_id      :string
#  lft            :integer          not null
#  rgt            :integer          not null
#  depth          :integer          default(0), not null
#  children_count :integer          default(0), not null
#  dataset        :string
#  default        :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Facility < ApplicationRecord
  acts_as_nested_set

  has_many :indicators

  validates :name_en, presence: true, uniqueness: true
  validates :name_km, presence: true, uniqueness: true
  validates :abbr_en, presence: true, uniqueness: true
  validates :abbr_km, presence: true, uniqueness: true

  before_create :secure_id
  before_validation :secure_parent_id

  scope :only_children, -> { where.not(parent_id: nil) }

  def name
    self["name_#{I18n.locale}"]
  end

  def abbreviation
    self["abbr_#{I18n.locale}"]
  end

  def locked?
    self.default?
  end

  private
    def secure_parent_id
      self.parent_id = parent_id.presence
    end
end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
  before_action :set_facility, only: %i[ edit update destroy ]

  def index
    @pagy, @facilities = pagy(authorize Facility.roots.reorder(sort_column + " " + sort_direction).includes(:children, :indicators))
  end

  def new
    @facility = authorize Facility.new
  end

  def edit
  end

  def create
    @facility = authorize Facility.new(facility_params)

    respond_to do |format|
      if @facility.save
        format.html { redirect_to facilities_url, notice: "Facility was successfully created." }
        format.json { render :show, status: :created, location: @facility }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @facility.update(facility_params)
        format.html { redirect_to facilities_url, notice: "Facility was successfully updated." }
        format.json { render :show, status: :ok, location: @facility }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @facility.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @facility.destroy

    respond_to do |format|
      format.html { redirect_to facilities_url, status: :see_other, notice: "Facility was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_facility
      @facility = authorize Facility.find(params[:id])
    end

    def facility_params
      params.require(:facility).permit(:id, :name_en, :name_km, :abbr_en, :abbr_km, :parent_id)
    end
end

app/helpers/facilities_helper.rb
module FacilitiesHelper
end

app/views/facilities/_facility.html.haml
.d-flex.facility
  .name{ class: ('sub-facility' unless facility.root?) }
    = "#{facility.name}"
    = "(#{facility.indicators.length})" unless facility.root?
  .w-25
    = "#{facility.abbr_en} (#{facility.abbr_km})"

  .flex-grow-1
    = timeago(facility.created_at).html_safe

  - if !facility.root? && policy(Indicator).create?
    = link_to facility_indicators_path(facility), class: "btn btn-circle btn-sm btn-outline-info me-1", data: { 'bs-toggle': 'tooltip', 'bs-placement': 'top' }, title: t('facility.manage_indicator') do
      %i.fas.fa-pencil-ruler

  / Edit button
  = render 'shared/buttons/edit_button', object: facility, url: edit_facility_path(facility)

  / Delete button
  - if facility.locked?
    %span{ data: { 'bs-toggle': 'tooltip', 'bs-placement': 'top' }, title: t('facility.already_in_used') }
      %button.btn.btn-circle.btn-sm.btn-outline-danger.disabled
        %i.fas.fa-trash-alt
  - else
    = render 'shared/buttons/delete_button', object: facility, message: { type: t('facility.facility'), name: facility.name, url: facility_path(facility) }

app/views/facilities/_form.html.haml
.w-50.view-center
  = simple_form_for @facility do |f|
    .mb-3= f.input :name_en, label: t('facility.name_en')
    .mb-3= f.input :name_km, label: t('facility.name_km')
    .mb-3= f.input :abbr_en, label: t('facility.abbr_en')
    .mb-3= f.input :abbr_km, label: t('facility.abbr_km')

    .mb-3.form-group
      %label= t('facility.parent')
      = f.select :parent_id, Facility.roots.pluck(:"name_#{I18n.locale}", :id), {:include_blank => true}, {class: 'form-select'}

    .actions
      = link_to t('shared.cancel'), facilities_path, class: 'btn btn-secondary me-1'
      = f.submit t('shared.save'), class: 'btn btn-primary'

app/views/facilities/edit.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('facility.edit_facility')
  = render 'form'

app/views/facilities/index.html.haml
.container-fluid.px-4.facilities
  = render 'shared/header_title', title: t('facility.facilities')

  .d-flex.justify-content-end.mb-2
    = render "shared/buttons/add_new_button", url: new_facility_path, name: t("facility.facility")

  .card.mb-4.pretty
    = render "shared/no_data", items: @facilities

    - if @facilities.present?
      .d-flex.facility-header
        %strong.name= sortable "name_#{I18n.locale}", t("facility.name")
        %strong.w-25= t("facility.abbreviation")
        %strong.flex-grow-1= t("shared.created_at")

      - @facilities.each do |facility|
        = render 'facility', facility: facility

        - facility.children.each do |child|
          = render 'facility', facility: child

    - if @pagy.pages > 1
      .pagy-wrapper.justify-content-lg-end.justify-content-center
        != pagy_bootstrap_nav(@pagy)

= render "shared/modals/confirm_delete_modal"

app/views/facilities/new.html.haml
.container-fluid.px-4.facilities.mb-4
  = render 'shared/header_title', title: t('facility.new_facility')
  = render 'form'

app/views/facilities/show.html.haml
= render "shared/modals/remote_modal", title: t('shared.confirm_delete', name: t('facility.facility')) do

  %div
    = t('shared.are_you_sure_to_delete', type: t('facility.facility'), name: @facility.name).html_safe

  .d-flex.justify-content-end.mt-3
    = render "shared/buttons/modal_cancel_button"
    = render "shared/buttons/modal_delete_button", item: @facility